#!/bin/bash
rpm -ivh https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/3.2/rhel/6/x86_64/zabbix-release-3.2-1.el6.noarch.rpm
yum install -y  zabbix-agent
sed -i 's/Server=127.0.0.1/Server=10.0.0.106/g;s/ServerActive=127.0.0.1/ServerActive=10.0.0.106/g;s/Hostname=Zabbix server/#Hostname=Zabbix server/g;s/# HostnameItem=system.hostname/HostnameItem=system.hostname/g;s/# HostMetadataItem=/HostMetadataItem=system.uname/g' /etc/zabbix/zabbix_agentd.conf
cat >/etc/hosts<<EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.0.0.100	php-web01
10.0.0.101	php-web02
10.0.0.102	tomcat-web01
10.0.0.103	tomcat-web02
10.0.0.104	keep01
10.0.0.105	keep02
10.0.0.106  Zabbix-server
10.0.0.107  mysql-server
EOF
/etc/init.d/zabbix-agent start
