#!/bin/bash
rpm -ivh https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/3.2/rhel/6/x86_64/zabbix-release-3.2-1.el6.noarch.rpm
yum install -y  zabbix-agent
sed -i 's/Server=127.0.0.1/Server=172.16.1.106/g;s/ServerActive=127.0.0.1/ServerActive=172.16.1.106/g;s/Hostname=Zabbix server/#Hostname=Zabbix server/g;s/# HostnameItem=system.hostname/HostnameItem=system.hostname/g;s/# HostMetadataItem=/HostMetadataItem=system.uname/g' /etc/zabbix/zabbix_agentd.conf
cat >/etc/hosts<<EOF
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
172.16.1.97   pptp-server
172.16.1.98   rsync-server
172.16.1.100	php-web01
172.16.1.101	php-web02
172.16.1.102	tomcat-web01
172.16.1.103	tomcat-web02
172.16.1.104	keep01
172.16.1.105	keep02
172.16.1.106  Zabbix-server
172.16.1.107  mysql-server
172.16.1.109  nfs-server
EOF
/etc/init.d/zabbix-agent start
